### ISSUE TITLE
请问如果有jpg或bmp格式的图片格式应该如何写makefile呢？

### ISSUE THREAD

**Issue by FranShavee** [BachWV/BachWV.github.io#1]
我直接写gcc -o src/*.jpg显示不能识别文件
file no recognize

**Comment by BachWV** [comment]
请问是acllib文章里的问题吗？您是想要添加图片以后重新编译吗？

**Comment by FranShavee** [comment]
似乎好像解决了，图片没法编译进文件里边，只能依靠运行程序时再去调用，命令行不能识别jpg这类文件

**Comment by BachWV** [comment]
读取图片是运行时哦，不是编译的时候做的事哦
